//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Client_Restaurant.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wserviceSoap", Namespace="http://tempuri.org/")]
    public partial class wservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getAllRestaurantOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostRestaurantOperationCompleted;
        
        private System.Threading.SendOrPostCallback PutRestaurantOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteRestaurantOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wservice() {
            this.Url = global::Client_Restaurant.Properties.Settings.Default.Client_Restaurant_localhost_wservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getAllRestaurantCompletedEventHandler getAllRestaurantCompleted;
        
        /// <remarks/>
        public event PostRestaurantCompletedEventHandler PostRestaurantCompleted;
        
        /// <remarks/>
        public event PutRestaurantCompletedEventHandler PutRestaurantCompleted;
        
        /// <remarks/>
        public event DeleteRestaurantCompletedEventHandler DeleteRestaurantCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllRestaurant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Restaurant[] getAllRestaurant() {
            object[] results = this.Invoke("getAllRestaurant", new object[0]);
            return ((Restaurant[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllRestaurantAsync() {
            this.getAllRestaurantAsync(null);
        }
        
        /// <remarks/>
        public void getAllRestaurantAsync(object userState) {
            if ((this.getAllRestaurantOperationCompleted == null)) {
                this.getAllRestaurantOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllRestaurantOperationCompleted);
            }
            this.InvokeAsync("getAllRestaurant", new object[0], this.getAllRestaurantOperationCompleted, userState);
        }
        
        private void OngetAllRestaurantOperationCompleted(object arg) {
            if ((this.getAllRestaurantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllRestaurantCompleted(this, new getAllRestaurantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PostRestaurant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PostRestaurant(string Nombre, string Direccion, string RNC, string Telefono, string Persona_Encargada, int Cantidad_Emplados, string Tipo_Comida, double Ventas_Mensuales_Promedio, string GuidReg, DateTime Fecha_Creacion, DateTime Fecha_Modificacion) {
            object[] results = this.Invoke("PostRestaurant", new object[] {
                        Nombre,
                        Direccion,
                        RNC,
                        Telefono,
                        Persona_Encargada,
                        Cantidad_Emplados,
                        Tipo_Comida,
                        Ventas_Mensuales_Promedio,
                        GuidReg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostRestaurantAsync(string Nombre, string Direccion, string RNC, string Telefono, string Persona_Encargada, int Cantidad_Emplados, string Tipo_Comida, double Ventas_Mensuales_Promedio, string GuidReg) {
            this.PostRestaurantAsync(Nombre, Direccion, RNC, Telefono, Persona_Encargada, Cantidad_Emplados, Tipo_Comida, Ventas_Mensuales_Promedio, GuidReg, null);
        }
        
        /// <remarks/>
        public void PostRestaurantAsync(string Nombre, string Direccion, string RNC, string Telefono, string Persona_Encargada, int Cantidad_Emplados, string Tipo_Comida, double Ventas_Mensuales_Promedio, string GuidReg, object userState) {
            if ((this.PostRestaurantOperationCompleted == null)) {
                this.PostRestaurantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostRestaurantOperationCompleted);
            }
            this.InvokeAsync("PostRestaurant", new object[] {
                        Nombre,
                        Direccion,
                        RNC,
                        Telefono,
                        Persona_Encargada,
                        Cantidad_Emplados,
                        Tipo_Comida,
                        Ventas_Mensuales_Promedio,
                        GuidReg}, this.PostRestaurantOperationCompleted, userState);
        }
        
        private void OnPostRestaurantOperationCompleted(object arg) {
            if ((this.PostRestaurantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostRestaurantCompleted(this, new PostRestaurantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PutRestaurant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PutRestaurant(int id, string Nombre, string Direccion, string RNC, string Telefono, string Persona_Encargada, int Cantidad_Emplados, string Tipo_Comida, double Ventas_Mensuales_Promedio, string GuidReg, DateTime Fecha_Creacion, DateTime Fecha_Modificacion) {
            object[] results = this.Invoke("PutRestaurant", new object[] {
                        id,
                        Nombre,
                        Direccion,
                        RNC,
                        Telefono,
                        Persona_Encargada,
                        Cantidad_Emplados,
                        Tipo_Comida,
                        Ventas_Mensuales_Promedio,
                        GuidReg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PutRestaurantAsync(int id, string Nombre, string Direccion, string RNC, string Telefono, string Persona_Encargada, int Cantidad_Emplados, string Tipo_Comida, double Ventas_Mensuales_Promedio, string GuidReg) {
            this.PutRestaurantAsync(id, Nombre, Direccion, RNC, Telefono, Persona_Encargada, Cantidad_Emplados, Tipo_Comida, Ventas_Mensuales_Promedio, GuidReg, null);
        }
        
        /// <remarks/>
        public void PutRestaurantAsync(int id, string Nombre, string Direccion, string RNC, string Telefono, string Persona_Encargada, int Cantidad_Emplados, string Tipo_Comida, double Ventas_Mensuales_Promedio, string GuidReg, object userState) {
            if ((this.PutRestaurantOperationCompleted == null)) {
                this.PutRestaurantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPutRestaurantOperationCompleted);
            }
            this.InvokeAsync("PutRestaurant", new object[] {
                        id,
                        Nombre,
                        Direccion,
                        RNC,
                        Telefono,
                        Persona_Encargada,
                        Cantidad_Emplados,
                        Tipo_Comida,
                        Ventas_Mensuales_Promedio,
                        GuidReg}, this.PutRestaurantOperationCompleted, userState);
        }
        
        private void OnPutRestaurantOperationCompleted(object arg) {
            if ((this.PutRestaurantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PutRestaurantCompleted(this, new PutRestaurantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteRestaurant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteRestaurant(int id) {
            object[] results = this.Invoke("DeleteRestaurant", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteRestaurantAsync(int id) {
            this.DeleteRestaurantAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteRestaurantAsync(int id, object userState) {
            if ((this.DeleteRestaurantOperationCompleted == null)) {
                this.DeleteRestaurantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteRestaurantOperationCompleted);
            }
            this.InvokeAsync("DeleteRestaurant", new object[] {
                        id}, this.DeleteRestaurantOperationCompleted, userState);
        }
        
        private void OnDeleteRestaurantOperationCompleted(object arg) {
            if ((this.DeleteRestaurantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteRestaurantCompleted(this, new DeleteRestaurantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Restaurant {
        
        private int idField;
        
        private string nombreField;
        
        private string direccionField;
        
        private string rNCField;
        
        private string telefonoField;
        
        private string persona_EncargadaField;
        
        private System.Nullable<int> cantidad_EmpladosField;
        
        private System.Nullable<System.DateTime> fecha_CreacionField;
        
        private System.Nullable<System.DateTime> fecha_ModificacionField;
        
        private string tipo_ComidaField;
        
        private System.Nullable<decimal> ventas_Mensuales_PromedioField;
        
        private string guidRegField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string RNC {
            get {
                return this.rNCField;
            }
            set {
                this.rNCField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string Persona_Encargada {
            get {
                return this.persona_EncargadaField;
            }
            set {
                this.persona_EncargadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Cantidad_Emplados {
            get {
                return this.cantidad_EmpladosField;
            }
            set {
                this.cantidad_EmpladosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha_Creacion {
            get {
                return this.fecha_CreacionField;
            }
            set {
                this.fecha_CreacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha_Modificacion {
            get {
                return this.fecha_ModificacionField;
            }
            set {
                this.fecha_ModificacionField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo_Comida {
            get {
                return this.tipo_ComidaField;
            }
            set {
                this.tipo_ComidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Ventas_Mensuales_Promedio {
            get {
                return this.ventas_Mensuales_PromedioField;
            }
            set {
                this.ventas_Mensuales_PromedioField = value;
            }
        }
        
        /// <remarks/>
        public string GuidReg {
            get {
                return this.guidRegField;
            }
            set {
                this.guidRegField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getAllRestaurantCompletedEventHandler(object sender, getAllRestaurantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Restaurant[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Restaurant[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PostRestaurantCompletedEventHandler(object sender, PostRestaurantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void PutRestaurantCompletedEventHandler(object sender, PutRestaurantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PutRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PutRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DeleteRestaurantCompletedEventHandler(object sender, DeleteRestaurantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteRestaurantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteRestaurantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591